### PR TITLE
Fixes Prepare > Column: Numeric > Row Statistics dialogue  Row statistics dialogue 

### LINKED ISSUE #7240: Improve the Prepare > Column: Numeric > Row Statistics dialogue
This started small, but has grown in what I consider to be a most satisfactory way.  Most changes are simple, but I hope @lilyclements can confirm my suggestions for the new R code and also provide (at least) some simple examples.

Here is the current dialogue:
image

Here is the corresponding R code:
```
# Code generated by the dialog, Row Summaries

row_summary <- base::apply(X=data_book$get_columns_from_data(data_name="Scores", col_names=c("BlueSky","Deducer","JASP","jamovi","RAF","Rattle","Rcmdr","R_Instat","RKWard"), force_as_data_frame=TRUE, use_current_filter=FALSE), MARGIN=1, FUN=mean)
data_book$add_columns_to_data(data_name="Scores", col_name="row_summary", col_data=row_summary, before=FALSE, adjacent_column="RKWard")

rm(row_summary)
```
My suggested changes to the dialogue are as follows:
a) Two radio buttons at the top.  Label first, namely `Summaries: `.  Then `Single` and `Multiple`
b) The Single option is what we have now, namely each row of data gives a single summary.  Multiple is new, described below.
c) In Single swap the `Count and Standard Deviation`.  Also change Number of Missing to `Number Missing`
d) (This needs confirmation from Lily).  Get rid of the User Defined button, but have a 9th radio button labelled User Defined.
e) If User defined is chosen, then open a drop down with a text field into which you can type a command.  The drop down can include   (some of) the 8 existing ones, plus a few more to be decided.
f) Now the code generated.  First the existing code has a very long first line.  Could you separate getting the data, from using it.  That is usually done.
g) Second is that we use apply.  We would like to use tidyverse when appropriate and dplyr has rowwise [here]
 (https://dplyr.tidyverse.org/articles/rowwise.html).  @lilyclements I assume we should use it?  I even wonder whether we could use code with a pipe in - as is usual in tidyverse?
h) in the user defined, could we include log?  @lilyclements Could we get both the log of the mean and the mean of the logs?

Part 2 - now the multiple, which was my starting point.
I wanted to get the ranks - row by row.
This produces 9 variables above and putting rank works fine.  So here we are producing 9 columns.  What else might we have?  Well deviations from mean, standardised values compared to the others in the rows.  Hopefully therefore Used Defined too.

I assume this will be a simple set of tasks after a Lily check?  So anyone could be assigned.

I am keen on this, because in our review I reminded Bob that we do have row statistics.  (It is one of his categories.)  So, before too many people look in detail I'd like to be sure we do it well!

### PR DESCRIPTION
**Pull request by EstherNjeriLiberatta**
Fixes #7240 
This is still a work in progress.

### CODE REVIEW

**Comment by EstherNjeriLiberatta** [comment]
@rdstern @lilyclements I have done the first part of the changes you requested with help from @N-thony i.e.
a.) Two radio buttons at the top. Label first, namely `Summaries: `. Then` Single` and` Multiple`
b) The Single option is what we have now, namely each row of data gives a single summary. 
c) In Single swap the Count and Standard Deviation. Also change Number of Missing to Number Missing
d) Get rid of the User Defined button, but have a 9th radio button labelled User Defined.
e) If User defined is chosen, then open a drop down with a text field into which you can type a command. The drop down can include (some of) the 8 existing ones, plus a few more to be decided.
f) Now the code generated. First, the existing code has a very long first line. Could you separate getting the data, from using it. 

Kindly review the work for any changes. Thank you.

**Review by rdstern — CHANGES_REQUESTED** [review]
@EstherNjeriLiberatta this looks good now.  I wonder about merging this version, and then attacking the other parts I put in the initial issue, and have now added to.  
So, could you just disable the Multiple button for now.  Then, in parallel, please could @shadrackkibet or @lloyddewit check the code, so it can be merged.  
I note (that's why I didn't see it) that the missing option is not visible, when you choose user defined.  That's fine now, but in the improvements, after merging, it should be available then - and included in the commands that will be generated.  (Not now, because the current list will change.)

File: instat/dlgRowSummary.vb [hunk 1]
```diff
@@ -120,5 +137,43 @@ Public Class dlgRowSummary
...
+            clsApplyFunction.RemoveParameterByName("FUN")
+        End If
+    End Sub
+
+    Private Sub ucrReceiverForRowSummaries_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverForRowSummaries.ControlValueChanged
+        ucrBase.clsRsyntax.lstBeforeCodes.Clear()
+        clsGetColumnsFunction = ucrReceiverForRowSummaries.GetVariables(True).Clone
+        clsGetColumnsFunction.SetAssignTo("columns")
+        clsApplyFunction.AddParameter("X", clsRFunctionParameter:=clsGetColumnsFunction, iPosition:=0)
+        ucrBase.clsRsyntax.AddToBeforeCodes(clsGetColumnsFunction)
```
Comment (shadrackkibet) [inline instat/dlgRowSummary.vb:177]: Perhaps I didn't understand the reason why this is done this way. Do you really need `clsGetColumnsFunction` function?  Isn't it just 

```
        ucrReceiverForRowSummaries.bForceAsDataFrame = True
        ucrReceiverForRowSummaries.SetParameterIsRFunction()
```

File: instat/dlgRowSummary.vb [hunk 2]
```diff
@@ -120,5 +137,43 @@ Public Class dlgRowSummary
...
+            clsOtherDummyFunction.AddParameter("checked", "sd", iPosition:=0)
+            clsApplyFunction.AddParameter("FUN", "sd", iPosition:=2)
+        ElseIf rdoSum.Checked Then
+            clsOtherDummyFunction.AddParameter("checked", "sum", iPosition:=0)
+            clsApplyFunction.AddParameter("FUN", "sum", iPosition:=2)
+        ElseIf rdoMedian.Checked Then
+            clsOtherDummyFunction.AddParameter("checked", "median", iPosition:=0)
+            clsApplyFunction.AddParameter("FUN", "median", iPosition:=2)
+        ElseIf rdoCount.Checked Then
+            clsOtherDummyFunction.AddParameter("checked", "count", iPosition:=0)
```
Comment (shadrackkibet) [inline instat/dlgRowSummary.vb:162]: - I also did some quick testing and got the below error when I selected `More` and in the drop-down selected `number missing`.
- This combo box should be non-editable.
- I also see the same summaries as the radio buttons repeated inside the combo box.

image

File: instat/dlgRowSummary.vb [hunk 3]
```diff
@@ -35,34 +39,38 @@ Public Class dlgRowSummary
...
         ucrBase.iHelpTopicID = 45
-        cmdUserDefined.Enabled = False ' temporarily disabled
-
-        'Setting receiver data types and parameters
-        ucrReceiverForRowSummaries.SetParameter(New RParameter("X", 0))
         ucrReceiverForRowSummaries.Selector = ucrSelectorForRowSummaries
         ucrReceiverForRowSummaries.SetMeAsReceiver()
         ucrReceiverForRowSummaries.strSelectorHeading = "Numerics"
         ucrReceiverForRowSummaries.SetIncludedDataTypes({"numeric"})
-        ucrReceiverForRowSummaries.bUseFilteredData = False
```
Comment (shadrackkibet) [inline instat/dlgRowSummary.vb:46]: Could you explain why was this removed?

**Review by shadrackkibet — CHANGES_REQUESTED** [review]

**Comment by rdstern** [comment]
@shadrackkibet said:
I also did some quick testing and got the below error when I selected More and in the drop-down selected number missing.
This combo box should be non-editable.
I also see the same summaries as the radio buttons repeated inside the combo box.

a) I asked (temporarily) for some of the same summaries.  But that will change in the next round, as specified in the issue (now).
b) Could delete the number missing, for now, if it gives an error.
c) The new items in the combo box will need the control to be editable.  So prefer that option to be kept.  (One example will be quantile,prob = 0.5, where the user could change that level to another value.

File: instat/dlgRowSummary.vb (hunk 3 above)
Comment (EstherNjeriLiberatta) [reply instat/dlgRowSummary.vb:46]: @shadrackkibet I had commented on it before to see whether there was a difference in the code. I might have removed it when cleaning the code. I'll add it back, thank you.

File: instat/dlgRowSummary.vb (hunk 1 above)
Comment (EstherNjeriLiberatta) [reply instat/dlgRowSummary.vb:177]: It was helpful when I was trying to separate the first line of code from the main function. 
 `ucrReceiverForRowSummaries.SetParameterIsRFunction()` didn't work as expected.

**Comment by EstherNjeriLiberatta** [comment]
Hello, @shadrackkibet I've fixed the changes you requested. I've also added an omit missing values control with no code yet. I will continue adding more features to the dialogue once it's merged. Kindly review. Thank you.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta pleased you are back to this dialogue.  I was puzzled by your comment on the addition of the Omit Missing Values , because that is already there for some of the options, and seems to be working.  It isn't visible on the More option, but I presume could be made so?

**Comment by EstherNjeriLiberatta** [comment]
@rdstern Yes it can, I will add it to the more option.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta has this version taken account of the rowwise suggestion from @lilyclements.  If not, then I would suggest you include that in the current pull request.  Then perhaps add at least some of the items suggested for the More before merging?  Good to discuss prehaps with @shadrackkibet if you need to.  Are you in Maseno, where he is now?

**Comment by EstherNjeriLiberatta** [comment]
@rdstern Okay. Yes, he is here, I have discussed this with him. Thank you for the feedback.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta should others have taken over this work?  There has been silence for a long time.  Are you still working?

**Comment by shadrackkibet** [comment]
@Vitalis95 @anastasia-mbithe @mmulahvictor I suggest one of you take over this task.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers Just a follow-up on this. Any volunteer to take over?

**Comment by EstherNjeriLiberatta** [comment]
@rdstern My apologies for the late reply. Yes, thank you for your patience. I'm working on this. @shadrackkibet I'll be working on this.

**Comment by shadrackkibet** [comment]
@EstherNjeriLiberatta we are reassigning all your tasks at the moment. I would suggest you don't do anything on this PR. 

The way forward is - Get in touch with Zach to clarify your work situation and respond to emails.

**Comment by EstherNjeriLiberatta** [comment]
@shadrackkibet Okay, thank you.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta there is still a fair bit to do on this dialogue, which I am very keen to include in the forthcoming update.  This includes the multiple option.  If you feel this may be too much work for you, then feel free to share with @N-thony.

**Comment by EstherNjeriLiberatta** [comment]
Okay, @rdstern  I will share it with him to work faster, thank you.

**Comment by EstherNjeriLiberatta** [comment]
@shadrackkibet I'm working on this with @N-thony.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern We've been having a challenge installing the matrixStats package on my laptop. @N-thony requesting your help to test the changes I've made. We are trying to fix the problem that's why it has been delayed but it should work okay on your end, just a few more adjustments on the dialogue. Thank you.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern This is ready for review. 
For testing I used the experimental_suvey dataset. You now have `rowwise()` instead of `apply()` for all functions in the single option as suggested by @lilyclements. New columns are no longer being added but instead you are updating the dataframe.
The Multiple option is using the `matrixStats` package. It has the three radio buttons: `Ranks`, `Ranges` and `Quantiles` all using `rowRanks()`, `row Ranges()`, and `rowQuantiles()` repsectively. You have additional combo boxes that is, `Ties` and `Type` for radio buttons `Ranks` and `Quantiles` respectively.

**Comment by rdstern** [comment]
@anastasia-mbithe this is looking really good.  There was a lot of work here.  Great job so far.  Just a bit of tidying needed!
a) Delete the mfv function, which gives an error if there is more than 1 mode in the data.
b) 2 of the functions allow the user to type.  They are the trimmed mean and the quantile.  But when I type anything it doesn't work, it gives a null function in the code.  For example changing quantile 0.5 to 0.4 or trimmed mean with 0.1 instead of 0.2.
c) Now a bigger problem, but easy to fix I hope?  The extra variable should add a variable to the existing dataframe.  In each case now it now does this, but then in a new data frame.
d) Now the multiple options.  
e) The ranks works - that's great!  In the dialogue, move the Ties control over a bit and make it wider.  Could you code it so the resulting variable names start with the original name, and add _r, say, for rank?  For the ranks there are as many new variables as there were variables.
f) For the range could the initial names be r_min and r_max?  (Of course they will be r_min1 and r_max1 is they already exist.
g) For quantiles the first pull-down could be made quite a lot wider, and the second could be much narrower.  Could the names perhaps be q0.2_, etc.  
h) I tried my own quantiles and they seem to work - great!

This is very good progress!  Well done indeed.

**Comment by EstherNjeriLiberatta** [comment]
> @anastasia-mbithe this is looking really good. There was a lot of work here. Great job so far. Just a bit of tidying needed! a) Delete the mfv function, which gives an error if there is more than 1 mode in the data. b) 2 of the functions allow the user to type. They are the trimmed mean and the quantile. But when I type anything it doesn't work, it gives a null function in the code. For example changing quantile 0.5 to 0.4 or trimmed mean with 0.1 instead of 0.2. c) Now a bigger problem, but easy to fix I hope? The extra variable should add a variable to the existing dataframe. In each case now it now does this, but then in a new data frame. d) Now the multiple options. e) The ranks works - that's great! In the dialogue, move the Ties control over a bit and make it wider. Could you code it so the resulting variable names start with the original name, and add _r, say, for rank? For the ranks there are as many new variables as there were variables. f) For the range could the initial names be r_min and r_max? (Of course they will be r_min1 and r_max1 is they already exist. g) For quantiles the first pull-down could be made quite a lot wider, and the second could be much narrower. Could the names perhaps be q0.2_, etc. h) I tried my own quantiles and they seem to work - great!
> 
> This is very good progress! Well done indeed.

@rdstern Thanks for your review, I will make the changes as requested but I guess tagged @anastasia-mbithe in this PR by mistake.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern, I noticed the issue you have mentioned in part **b**. It is one of the challenges I experienced. I'm working on fixing it by finding a way in Visual Studio so that when you change it, it also changes the R code. I'm looking into it with help from @N-thony. Thanks again for your review.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta ooops, you are right, I mentioned ana by mistake.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta just to confirm that the bottom control currently is:

image

Currently that's the name of the new data frame - which we don't need.  The new column name is currently not row_summary, but the name of the summary itself, which is great and just what we need.  So the change may be in the control, but keep the column summary name as you have it now.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern, @Ivanluv is suggesting that we have an `nud` control for the parameters in the mean and quantile functions rather than typing in the input. It will look like this:

**Comment by EstherNjeriLiberatta** [comment]
@rdstern @lilyclements This is ready for review.
I have made the changes you requested that is;
**For the Single Option**:
a) Delete the `mfv` function, which gave an error if there is more than 1 mode in the data.
b) Fixed the two functions that allow the user to type in i.e. trim mean and quantile.
c) The extra variable is adding a variable to the existing data frame. 
**For the multiple option**.
a) Moved the Ties control over a bit and make it wider. 
b) Coded it so the resulting variable names start with the original name, and added r, say, for rank.
c) For the range, coded the initial names to be r_min and r_max.
d) For quantile, made the first pull-down a lot wider, and the second much narrower. 
e)Coded the names to be q0.2, etc.

File: instat/dlgRowSummary.vb [hunk 4]
```diff
@@ -35,68 +48,357 @@ Public Class dlgRowSummary
...
+        dctTiesValues.Add("min", Chr(34) & "min" & Chr(34))
+        ucrInputTiesMethod.SetItems(dctTiesValues)
+        ucrInputTiesMethod.bAllowNonConditionValues = True
+        ucrInputTiesMethod.SetDropDownStyleAsNonEditable()
+
+        'function ran here is probs = c(VALUES)
+        ucrInputProbability.SetParameter(New RParameter("p", 1, bNewIncludeArgumentName:=False))
+        ucrInputProbability.AddQuotesIfUnrecognised = False
+        ucrInputProbability.SetValidationTypeAsNumericList()
+        ucrInputProbability.SetDropDownStyleAsNonEditable()
```
Comment (lilyclements) [inline instat/dlgRowSummary.vb:85]: I think this should be editable still, so this line can be removed. We just need to have it in the TestOkEnabled to check it isn't empty (when the multiple rdo is checked)

File: instat/dlgRowSummary.vb [hunk 5]
```diff
@@ -35,68 +48,357 @@ Public Class dlgRowSummary
...
-            ucrBase.OKEnabled(True)
+        If rdoSingle.Checked Then
+            If Not ucrReceiverForRowSummaries.IsEmpty AndAlso ucrSaveNewDataFrame.IsComplete AndAlso ucrInputUserDefined.GetText <> "" Then
+                ucrBase.OKEnabled(True)
+            Else
+                ucrBase.OKEnabled(False)
+            End If
         Else
-            ucrBase.OKEnabled(False)
+            If Not ucrReceiverForRowSummaries.IsEmpty Then
```
Comment (lilyclements) [inline instat/dlgRowSummary.vb:397]: Should include ucrInputProbability here. So can change this to:
`            If Not ucrReceiverForRowSummaries.IsEmpty AndAlso ucrInputProbability.GetText <> "" Then`

And also add `ucrInputProbability.ControlContentsChanged` later for TestOK sub.

**Review by lilyclements — COMMENTED** [review]
Looks good! Just two very minor comments

**Review by rdstern — CHANGES_REQUESTED** [review]
Looks good.
a) TRimmed mean make maximum 0.5 with steps of 0.01
b) Quantile ok from 0 to 1, but steps of 0.01.
c) Multiple, label, change quantile to quantiles

File: instat/dlgRowSummary.vb [hunk 6]
```diff
@@ -35,68 +48,354 @@ Public Class dlgRowSummary
...
-            ucrBase.OKEnabled(True)
+        If rdoSingle.Checked Then
+            If Not ucrReceiverForRowSummaries.IsEmpty AndAlso ucrSaveNewDataFrame.IsComplete AndAlso ucrInputUserDefined.GetText <> "" Then
+                ucrBase.OKEnabled(True)
+            Else
+                ucrBase.OKEnabled(False)
+            End If
         Else
-            ucrBase.OKEnabled(False)
+            If Not ucrReceiverForRowSummaries.IsEmpty AndAlso ucrInputProbability.GetText <> "" Then
```
Comment (lilyclements) [inline instat/dlgRowSummary.vb:394]: Change `AndAlso ucrInputProbability.GetText <> "" Then` to

`AndAlso ((rdoRowQuantile.IsChecked AndAlso ucrInputProbability.GetText <> "") OrElse Not rdoRowQuantile.IsChecked) Then`

This would mean that OK is disabled when the ucrInput is empty only if the ucrInput is visible (that is, if the rdoRowQuantile is checked)

File: instat/dlgRowSummary.vb [hunk 7]
```diff
@@ -106,19 +405,220 @@ Public Class dlgRowSummary
...
+        clsRowQuantilesFunction.AddParameter("probs", "c(" & ucrInputProbability.GetText & ")", iPosition:=1)
+        AddConcatenateParameters()
+    End Sub
+
+    Private Sub ucrSelectorForRowSummaries_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrSelectorForRowSummaries.ControlValueChanged
+        clsAddColumnsFunction.AddParameter("data_name", Chr(34) & ucrSelectorForRowSummaries.ucrAvailableDataFrames.cboAvailableDataFrames.Text & Chr(34), iPosition:=0)
+    End Sub
+
+    Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverForRowSummaries.ControlContentsChanged, ucrPnlStatistics.ControlContentsChanged,
+        ucrSaveNewDataFrame.ControlContentsChanged, ucrInputProbability.ControlContentsChanged, ucrInputUserDefined.ControlContentsChanged, ucrPnlMultipleRowSummary.ControlContentsChanged, ucrPnlRowSummaries.ControlContentsChanged
```
Comment (lilyclements) [inline instat/dlgRowSummary.vb:621]: Add in here `ucrPnlMultipleRowSummary.ControlContentsChanged` due to suggested changes in the TestOK

**Review by lilyclements — COMMENTED** [review]
Looks good! One or two final comments

**Comment by EstherNjeriLiberatta** [comment]
Fixed the Nud to have an increment of 0.01 for both mean and quantile in the single option.
Changed the maximum value for the trimmed mean to 0.5.
Fixed bug on test okay.
@rdstern This is ready for review.

**Comment by EstherNjeriLiberatta** [comment]
Changed Quantile to Quantiles on the multiple option. 
@rdstern @africanmathsinitiative/developers this is ready for review

**Review by rdstern — APPROVED** [review]
Great.  Really good if this could be included in the forthcoming version

**Comment by lloyddewit** [comment]
@lilyclements Thank you for your review.
You have 4 open comments above. Please could you check if they've been satisfactorily resolved, and if so, click on their 'Resolve conversation' buttons.
Thanks!

File: instat/dlgRowSummary.vb (hunk 5 above)
Comment (lilyclements) [reply instat/dlgRowSummary.vb:395]: @EstherNjeriLiberatta have you added this in?

**Comment by lilyclements** [comment]
@lloyddewit thanks. I am happy that the comments I made are resolved.

**Comment by rdstern** [comment]
@lloyddewit given @lilyclements comments above is this ok to approve now?

File: instat/dlgRowSummary.vb [hunk 8]
```diff
@@ -106,19 +414,220 @@ Public Class dlgRowSummary
...
             End If
+            ucrBase.clsRsyntax.SetBaseROperator(clsPipeOperator)
         Else
-            clsApplyFunction.RemoveParameterByName("na.rm")
+            If rdoMultiple.Checked Then
+                If rdoRowRange.Checked Then
+                    clsDummyRowFunction.AddParameter("check", "rowRange", iPosition:=0)
+                    clsColumnNamesFunction.AddParameter("x", clsRFunctionParameter:=clsRowRangesFunction, iPosition:=0, bIncludeArgumentName:=False)
+                    ucrBase.clsRsyntax.SetBaseROperator(clsAssignOperator)
+
```
Comment (lloyddewit) [inline instat/dlgRowSummary.vb:542]:
```suggestion
```

**Review by lloyddewit — APPROVED** [review]
