### PR TITLE
Opening Script from Script Window 

### LINKED ISSUE #4115: Making the script window editable
This is not just from me, but now from David!  We think it is a good possible task for Maxwell?

It is to make the Script window editable.
Then to be able to submit (run) either the window or the selected section.

According to David there are then 3 or 4 ways this could be run.  So the alternatives would be on a right-click menu.
There is then a health warning that running after editing the code carries a health risk.  Do you want to continue.  Like the warning when you delete columns.

But if it crashes we do now have our recovery options, so that's a good thing!

### PR DESCRIPTION
**Pull request by maxwellfundi**
@africanmathsinitiative/developers  this is ready for review. 

To test it, run the software and send something to script, then from the script window right click > Open Script

Fixes #4115

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons  I have gotten the script to open including adding the top 3 lines to set up. My query is that, how will i have now to extract the data that is being used in the script. 

For example in this case, i loaded the Survey data, and produced a boxplot, then I went back to the boxplot and did ToScript, which i have run and opened in RStudio like shown here. 

On the import dialog, i did not sent anything to script and so there Survey  could not be foung when i run this script. 

Assuming that someone may do this more than once. (Sending things to script) and from different dialogs which are using different dataframes, how can we extract the data from the instatobject so that the script doesnt throw an error. 

Whats your opinion?
 
`setwd(dir="C:/Users/Fundi/Source/Repos/R-Instat/instat/bin/Debug/static/InstatObject/R")
source(file="Rsetup.R")
InstatDataObject <- instat_object$new()
# Code generated by the dialog, Boxplot

survey <- InstatDataObject$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(y=Yield, fill=Fertgrp., x=Village.)) + ggplot2::geom_boxplot() + theme_grey()
InstatDataObject$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
InstatDataObject$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))`

**Comment by dannyparsons** [comment]
By opinion is quite simple, that's for the user to worry about. If they take a partial script into R then they need to sort out getting it to work. If that's not something they yet understand how to do then they probably shouldn't be using the script in this way.
I don't think this should be a button because I don't think it will be used that much. It's only slightly quicker than doing copy and paste so I'd be happy if it was on the right click. Then it's slightly hidden and won't confuse users as much.

**Comment by shadrackkibet** [comment]
Testing this.

**Comment by maxwellfundi** [comment]
Great thanks.

**Comment by shadrackkibet** [comment]
**Just two  quick things to note:**

This perfectly opens in R as expected. 
1. when you right click and click on **clear contents** the message box doesn't display full message , some contents are hidden.
image
2.I see **Run selected text** is enabled when no text is selected.I think it should be disabled at this instance.

**Comment by maxwellfundi** [comment]
@shadrackkibet  I have now addressed the issues on the message box. I have also added the message to show when no text is selected. 

About not seeing the selected text when the message box appears i think its generally how it works but these could be features we can look at in the future. 

@dannyparsons  this is now ready for you.

**Comment by dannyparsons** [comment]
This sounds good. Can someone test the changes are ok?

**Comment by Patowhiz** [comment]
Yeah sure. @shadrackkibet should I tackle this or you are on it.

**Comment by shadrackkibet** [comment]
@Patowhiz  you can go ahead and test this.

**Comment by Patowhiz** [comment]
Okay

File: instat/ucrScript.vb [hunk 1]
```diff
@@ -41,7 +41,7 @@ Public Class ucrScript
     Private Sub mnuRunWholeScript_Click(sender As Object, e As EventArgs) Handles mnuClearContents.Click
         Dim dlgResponse As DialogResult
         If txtScript.Text <> "" Then
-            dlgResponse = MessageBox.Show("Are you sure you want to clear the " & Me.Text, "Clear " & Me.Text, MessageBoxButtons.YesNo)
+            dlgResponse = MessageBox.Show("Are you sure you want to clear the contents of the script window " & Me.Text, "Clear " & Me.Text, MessageBoxButtons.YesNo)
```
Comment (shadrackkibet) [inline instat/ucrScript.vb]: I think this is a question we should have a question mark at the end.

Comment (Patowhiz) [reply instat/ucrScript.vb]: @maxwellfundi @dannyparsons  I think the best way will be to have the icon of the MessageBox be a question mark, rather than the "?". Or any other icon that expresses the message. The MessageBox has default icons that can be used.

Comment (maxwellfundi) [reply instat/ucrScript.vb]: I think we need to be consistent with our message boxes. We have not thought about that really but i agree we might want to have a question mark other than the warning sign.

Comment (maxwellfundi) [reply instat/ucrScript.vb]: Thos is what we got now. 

image

Comment (shadrackkibet) [reply instat/ucrScript.vb]: @dannyparsons  this is ready for you to review.

**Comment by Patowhiz** [comment]
@dannyparsons I think the changes are are okay. The dialogue works correctly and the issues have been addressed

**Comment by dannyparsons** [comment]
Looks good, and I like the question mark icon. We should use this whenever we have questions in message boxes.

**Comment by Patowhiz** [comment]
Yeah. VB.NET has a couple of the icons. And you can have custom made for
rinstant. People react to and understand visuals much better than plain
text.
