### PR TITLE
Fixed bug in the Start of Rains Dialog

### LINKED ISSUE #7488: Bug in the Start of Rains Dialogue
We encountered this bug during the GMet workshop, this bug is found in the `0.7.5` version of R-instat but not in the older version (`0.7.4` seems to work fine)
Start of Rains Bug

This bug occurred when we used the` Start of Rain` dialogue
1. Go to 'Climatic'
2. Click on 'Prepare'
3. Scroll down and select 'Start of Rains'
4. input the necessary Variables and conditions
5. The error is in the above the screenshot
Screenshot (427)

The R commands for this dialogue in the `0.7.5` version seem to work fine for the `0.7.4` version.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7488 
@lilyclements thanks for your support, @rdstern I had a quick look of it then requested help from Lily, this seems to be fixed now, please take a look.
@derekagorhom @VimbayiChimonyo could you also test?
@dannyparsons could you review this? Thanks.

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@N-thony this looks to be fixed.  So I am approving.  I hope that @ChrisMarsh82 can check and merge.
I did notice that the dialogue ignores a filter, if one is applied.  I checked back and this is also the case in Version 0.7.4, so perhaps to be examined later.

**Comment by VimbayiChimonyo** [comment]
@N-thony forgive my ignorance - so do I run the script in R-INSTAT or do I download it again.

**Comment by VimbayiChimonyo** [comment]
@N-thony I tested and it is now working. Thank you

**Comment by ChrisMarsh82** [comment]
@shadrackkibet could you review this? Its R code which would be better for you to approve

File: instat/static/InstatObject/R/Backend_Components/calculations.R [hunk 1]
```diff
@@ -476,38 +476,42 @@ DataBook$set("public", "apply_instat_calculation", function(calc, curr_data_list
...
-    } else if (any(stringr::str_detect("Date", col_data_type))){
-      # put in here the ones that DO NOT work for date
-      if (any(grepl("summary_sum", formula_fn_exp))){
-        curr_data_list[[c_data_label]] <- curr_data_list[[c_data_label]] %>%
-          dplyr::summarise_(.dots = setNames(list(NA), calc$result_name))
+    if (exists(deparse(substitute(col_name)), parent.frame())){
+      # get the data type of the column
+      col_data_type <- self$get_variables_metadata(data_name = calc_from_data_name, column = col_name, property = "class")
+      # if it is a ordered factor...
+      if (any(stringr::str_detect("ordered", col_data_type))){
```
Comment (shadrackkibet) [inline instat/static/InstatObject/R/Backend_Components/calculations.R:483]: There is a problem with these variable type checks. This is relying on obtaining the string from the metadata. I find this unsafe and might be difficult to maintain in future. For example, if we change how we display these variable types in the metadata then these checks will all be invalid.

A "correct" and safe way is to check the class of the column itself using `is.numeric(), is.factor()` etc

Comment (lilyclements) [reply instat/static/InstatObject/R/Backend_Components/calculations.R:483]: @shadrackkibet I do agree, but the issue with that is that this line is called in the `summary_tables` function. In that function, everything is converted to a character to create the summary tables. This is to allow for the calculations to take place without losing classes or gettings NA's (for example, for `date` variables). I'm happy to go through this in more detail if you'd like!

Comment (shadrackkibet) [reply instat/static/InstatObject/R/Backend_Components/calculations.R:483]: Great and thanks for giving more context. Please check my analysis below; 

`col_name` is always a single character therefore `col_data_type` will always be a single character which then means `any()` is redundant? but perhaps just for safety, it is better to have. I also find it unsafe to use `str_detect` here because this detects a pattern which means "partial" matching is then allowed for example `stringr::str_detect("ordered", "order")` will return `TRUE`. 

I suggest we use a strict check like `identical("ordered",col_data_type)` or just `"ordered"==col_data_type`? 
What do you think?

Comment (shadrackkibet) [reply instat/static/InstatObject/R/Backend_Components/calculations.R:483]: @lilyclements that's correct. But it is still beneficial to change to `identical()` or `%in%` and collapse with `any` instead of `str_detect`?

Comment (lilyclements) [reply instat/static/InstatObject/R/Backend_Components/calculations.R:483]: I'm getting that `identical` gives a `FALSE`:

```
col_data_type <- c("ordered", "factor")

any(identical("ordered", col_data_type))
any(str_detect("ordered", col_data_type))
```

But yes, happy to change it to `%in%`

`any("ordered" %in% col_data_type)`

Comment (shadrackkibet) [reply instat/static/InstatObject/R/Backend_Components/calculations.R:483]: What about `any(c("ordered", "character") %in% col_data_type)`?

Comment (lilyclements) [reply instat/static/InstatObject/R/Backend_Components/calculations.R:483]: That would cause problems if we had a variable that was a factor, but not ordered

```
col_data_type <- c("factor")
any(c("ordered", "factor") %in% col_data_type)
```

**Review by shadrackkibet — APPROVED** [review]
@rdstern if you test and re-approve then we can merge.

**Review by rdstern — APPROVED** [review]
That's a big relief.  I have been using it on data from Zambia and it seems to work fine now.
