### PR TITLE
Fixes presentation issues in french translation in all dialogs under climatic menu

### LINKED ISSUE #6473: Improving the consistency of our dialogues?
This suggestion relates to 2 existing issues.  Namely:
1) The comments below in issue #6469  and 2) a comment #6472 on implementing a dialogue in the standard way.

@lloyddewit I suggest after this being merged, to work on the Climatic menu in one PR.

@N-thony Thanks, good idea
Please could you try and resolve the remaining parts of issue #6454, issue #6464 and issue #6465; and then start checking/updating the dialogs in the Climatic menu?

@rdstern Is that OK from your side or did you have a different task you'd prefer @N-thony to work on?

I like to propose a slightly different system that examines dialogues for a number of aspects at the same time. 

My suggestion is to work dialogue-by-dialogue, rather than menu by menu.  In each "offending" dialogue, whenever there is anyone of the following points, then the list below is checked.  An issue is made for that dialogue, with the new Consistency label.  And a variety of aspects are checked - and if necessary - corrected at the same time.  In future then we will steadily go through quite a lot of the dialogues and those that are checked will all have the consistency label attached.

So here is my initial list of checks:
a)  Implementation is in the "standard" way.
b) Labels are appropriate length for the French.
c) The new Save control - when relevant - is completed and saves the new variable(s) in a consistent way.
d) Spacing of controls on the dialogue is consistent and well aligned.

Are there other topics to add?  What do you think?
If so, then this will be quite a bit of work.  It could wait (perhaps, or just be tested) until the next level of translation is available?  Then a dialogue for checking is "triggered" by any of the above aspects.  But once triggered each of the above is considered.  The pull request when triggered by labels can just report "Implementation is already standard".

### PR DESCRIPTION
**Pull request by N-thony**
Partially fixes #6473
@rdstern this PR fix the presentation problems when texts are translated in French. Could have a look? Thanks.

### CODE REVIEW

File: instat/dlgClimaticBoxPlot.vb [hunk 1]
```diff
@@ -554,4 +554,16 @@ Public Class dlgClimaticBoxPlot
...
+
+    End Sub
+
+    Private Sub ucrInput_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrInputYear.ControlValueChanged, ucrInputWithinYear.ControlValueChanged, ucrInputStation.ControlValueChanged
+
+    End Sub
+
+    Private Sub ucrPnlPlots_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrPnlPlots.ControlValueChanged
+
+    End Sub
```
Comment (lloyddewit) [inline instat/dlgClimaticBoxPlot.vb:568]: Not needed, remove?
```suggestion
```

File: instat/dlgClimaticSummary.vb [hunk 2]
```diff
@@ -333,6 +333,10 @@ Public Class dlgClimaticSummary
         sdgMissingOptions.ShowDialog()
     End Sub
 
+    Private Sub Receivers_controlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverYear.ControlValueChanged, ucrReceiverWithinYear.ControlValueChanged, ucrReceiverStation.ControlValueChanged, ucrReceiverElements.ControlValueChanged
+
+    End Sub
+
```
Comment (lloyddewit) [inline instat/dlgClimaticSummary.vb:339]: remove?
```suggestion
```

File: instat/dlgOneWayFrequencies.vb [hunk 3]
```diff
@@ -266,4 +266,8 @@ Public Class dlgOneWayFrequencies
     Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverWeights.ControlContentsChanged, ucrChkWeights.ControlContentsChanged, ucrNudGroups.ControlContentsChanged, ucrChkGroupData.ControlContentsChanged, ucrReceiverOneWayFreq.ControlContentsChanged, ucrSaveGraph.ControlContentsChanged
         TestOkEnabled()
     End Sub
+
+    Private Sub grpSort_Enter(sender As Object, e As EventArgs) Handles grpSort.Enter
+
+    End Sub
```
Comment (lloyddewit) [inline instat/dlgOneWayFrequencies.vb:272]: remove?
```suggestion
```

File: instat/dlgScatterPlot.vb [hunk 4]
```diff
@@ -269,4 +269,8 @@ Public Class dlgScatterPlot
     Private Sub ucrVariablesAsFactorForScatter_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrVariablesAsFactorForScatter.ControlContentsChanged, ucrReceiverX.ControlContentsChanged
         ' CheckIfNumeric()
     End Sub
+
+    Private Sub ucrSaveScatterPlot_ContentsChanged(ucrChangedControl As ucrCore) Handles ucrVariablesAsFactorForScatter.ControlContentsChanged, ucrSaveScatterPlot.ControlContentsChanged, ucrReceiverX.ControlContentsChanged
+
+    End Sub
```
Comment (lloyddewit) [inline instat/dlgScatterPlot.vb:275]: remove?
```suggestion
```

**Review by lloyddewit — COMMENTED** [review]
@N-thony This looks good. I thing VS automatically added some unnecessary handlers. Can we delete them?

File: instat/dlgHistogram.vb [hunk 5]
```diff
@@ -254,12 +254,12 @@ Public Class dlgHistogram
...
             cmdHistogramOptions.Text = "Histogram Options"
-            cmdHistogramOptions.Size = New Size(120, 25)
+            'cmdHistogramOptions.Size = New Size(120, 25)
         ElseIf rdoDensity.Checked Then
-            cmdHistogramOptions.Size = New Size(120, 25)
+            'cmdHistogramOptions.Size = New Size(120, 25)
             cmdHistogramOptions.Text = "Density Options"
         ElseIf rdoFrequencyPolygon.Checked Then
-            cmdHistogramOptions.Size = New Size(160, 25)
+            'cmdHistogramOptions.Size = New Size(160, 25)
```
Comment (lloyddewit) [inline instat/dlgHistogram.vb:262]: I assume this resize is no longer needed because you made the label permanently larger to cope with French text. If these lines aren't needed, then can we delete them?

**Review by lloyddewit — CHANGES_REQUESTED** [review]

File: instat/dlgHistogram.vb (hunk 5 above)
Comment (N-thony) [reply instat/dlgHistogram.vb]: @lloyddewit I removed these lines. Please have a look. Thanks.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern Please could you test? thanks

**Review by rdstern — APPROVED** [review]

**Review by rdstern — APPROVED** [review]
