### PR TITLE
Fixing when OK is enabled in the Start of Rains dialog

### LINKED ISSUE #5925: Start of Rains - OK enabled bug
**Describe the bug**
I came across a minor bug in the "start of rains" dialog where I think OK is enabled in a situation which it should not be. However, I wanted to check in case the issue is instead with the code.

**To Reproduce**
1. Import the Ghana data,
2. Open the Start of Rains dialog, the "station", "date", and "rain" columns are filled.
3. Click to display "Day of Year" and "Date"
4. Click OK

An error comes up since the "day of year" column is not filled in the dialog.
This column needs to be filled because the dialog filters to the days in the year selected from the "Day Range" option.

@rdstern - presumably OK should never be enabled until the "day of year" column is filled. Is this correct?

### PR DESCRIPTION
**Pull request by lilyclements**
Fixes #5925 

@africanmathsinitiative/developers this is ready to review

In this PR, the TestOK is changed after a minor bug was spotted.

### CODE REVIEW

**Review by Wycklife — DISMISSED** [review]
This is working fine.

**Comment by Karakacha** [comment]
I have also tested this and its working.

**Review by Karakacha — APPROVED** [review]
I tested it and it worked

File: instat/dlgStartofRains.vb [hunk 1]
```diff
@@ -763,25 +763,19 @@ Public Class dlgStartofRains
...
+        If Not ucrReceiverRainfall.IsEmpty AndAlso Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverDOY.IsEmpty AndAlso Not ucrReceiverYear.IsEmpty AndAlso ucrNudThreshold.GetText <> "" AndAlso ((ucrChkNumberOfRainyDays.Checked AndAlso ucrNudRDMinimumDays.GetText <> "" AndAlso ucrNudRDOutOfDays.GetText <> "") OrElse Not ucrChkNumberOfRainyDays.Checked) AndAlso (((ucrChkTotalRainfall.Checked AndAlso ucrNudTROverDays.GetText <> "") AndAlso ((rdoTRAmount.Checked AndAlso ucrNudTRAmount.GetText <> "") OrElse (rdoTRPercentile.Checked AndAlso ucrNudTRPercentile.GetText <> ""))) OrElse Not ucrChkTotalRainfall.Checked) AndAlso ((ucrChkDrySpell.Checked AndAlso ucrNudDSMaximumDays.GetText <> "" AndAlso ucrNudDSLengthOfTime.GetText <> "") OrElse Not ucrChkDrySpell.Checked) AndAlso ((ucrChkDryPeriod.Checked AndAlso ucrNudDPMaxRain.GetText <> "" AndAlso ucrNudDPRainPeriod.GetText <> "" AndAlso ucrNudDPOverallInterval.GetText <> "") OrElse Not ucrChkDryPeriod.Checked) Then
```
Comment (lloyddewit) [inline instat/dlgStartofRains.vb:766]: I find one long line unreadable. A simple improvement would be to split it onto multiple lines (see below).
It would be even better to refactor this sub and simplify the logic. Could we set `bOKEnabled` to false on line 765, and then just pick out the conditions where `bOkEnabled` is true?
```suggestion
        If Not ucrReceiverRainfall.IsEmpty AndAlso
                Not ucrReceiverDate.IsEmpty AndAlso
                Not ucrReceiverDOY.IsEmpty AndAlso
                Not ucrReceiverYear.IsEmpty AndAlso
                ucrNudThreshold.GetText <> "" AndAlso
                (
                    (ucrChkNumberOfRainyDays.Checked AndAlso ucrNudRDMinimumDays.GetText <> "" AndAlso ucrNudRDOutOfDays.GetText <> "") OrElse
                    Not ucrChkNumberOfRainyDays.Checked) AndAlso
                (
                    (
                        (ucrChkTotalRainfall.Checked AndAlso ucrNudTROverDays.GetText <> "") AndAlso
                        ((rdoTRAmount.Checked AndAlso ucrNudTRAmount.GetText <> "") OrElse (rdoTRPercentile.Checked AndAlso ucrNudTRPercentile.GetText <> ""))) OrElse
                    Not ucrChkTotalRainfall.Checked) AndAlso
                (
                    (ucrChkDrySpell.Checked AndAlso ucrNudDSMaximumDays.GetText <> "" AndAlso ucrNudDSLengthOfTime.GetText <> "") OrElse
                    Not ucrChkDrySpell.Checked) AndAlso
                (
                    (ucrChkDryPeriod.Checked AndAlso ucrNudDPMaxRain.GetText <> "" AndAlso ucrNudDPRainPeriod.GetText <> "" AndAlso ucrNudDPOverallInterval.GetText <> "") OrElse
                    Not ucrChkDryPeriod.Checked) Then
```

File: instat/dlgStartofRains.vb [hunk 2]
```diff
@@ -763,25 +763,19 @@ Public Class dlgStartofRains
...
-                bOkEnabled = False
-            End If
+        If Not (ucrChkAsDoy.Checked OrElse ucrChkAsDate.Checked OrElse ucrChkStatus.Checked) Then
+            bOkEnabled = False
         End If
-        If ucrChkStatus.Checked Then
-            If ucrInputNewStatusColumnName.IsEmpty Then
-                bOkEnabled = False
-            End If
+        If (ucrChkAsDoy.Checked AndAlso ucrInputNewDoyColumnName.IsEmpty) OrElse (ucrChkAsDate.Checked AndAlso ucrInputNewDateColumnName.IsEmpty) OrElse (ucrChkStatus.Checked AndAlso ucrInputNewStatusColumnName.IsEmpty) Then
```
Comment (lloyddewit) [inline instat/dlgStartofRains.vb:777]: Make more readable?
```suggestion
        If (ucrChkAsDoy.Checked AndAlso ucrInputNewDoyColumnName.IsEmpty) OrElse
                (ucrChkAsDate.Checked AndAlso ucrInputNewDateColumnName.IsEmpty) OrElse
                (ucrChkStatus.Checked AndAlso ucrInputNewStatusColumnName.IsEmpty) Then
            bOkEnabled = False
        End If
```

**Review by lloyddewit — CHANGES_REQUESTED** [review]

File: instat/dlgStartofRains.vb (hunk 1 above)
Comment (lilyclements) [reply instat/dlgStartofRains.vb:766]: I don't think I follow the final suggestion - picking out conditions where `bOkEnabled` is true is what is being run here, with additional false conditions given below?
I'm happy to commit these changes if you think that's easiest.

**Review by lloyddewit — APPROVED** [review]

File: instat/dlgStartofRains.vb (hunk 1 above)
Comment (lloyddewit) [reply instat/dlgStartofRains.vb]: @lilyclements I don't blame you :) Your suggestion sounds reasonable and I committed the suggested changes.

**Comment by lloyddewit** [comment]
@rdstern Please could you test? thanks

File: instat/dlgStartofRains.vb [hunk 3]
```diff
@@ -763,25 +763,41 @@ Public Class dlgStartofRains
...
-            If ucrInputNewStatusColumnName.IsEmpty Then
-                bOkEnabled = False
-            End If
+        If (ucrChkAsDoy.Checked AndAlso ucrInputNewDoyColumnName.IsEmpty) OrElse
+                (ucrChkAsDate.Checked AndAlso ucrInputNewDateColumnName.IsEmpty) OrElse
+                (ucrChkStatus.Checked AndAlso ucrInputNewStatusColumnName.IsEmpty) Then
+            bOkEnabled = False
+        End If
+            bOkEnabled = False
         End If
```
Comment (shadrackkibet) [inline instat/dlgStartofRains.vb:801]: Syntax error with this `if` statement.

**Review by shadrackkibet — CHANGES_REQUESTED** [review]

File: instat/dlgStartofRains.vb (hunk 3 above)
Comment (lilyclements) [reply instat/dlgStartofRains.vb]: Good point - have sorted it now, thanks.

**Review by shadrackkibet — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@lloyddewit please re-approve and merge.

**Comment by lloyddewit** [comment]
@rdstern This PR is a releatively small change which has been tested by others. However, there have been some changes since the last test, and this PR hasn't been tested yet by you. 
Please could you test/approve? thanks

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern please can we wait for @rdstern 's approval before we merge? thanks

**Review by rdstern — APPROVED** [review]
