### PR TITLE
Fixed bug in selecting of all factors

### LINKED ISSUE #7538: Select all levels control for a factor doesn't seem to work now
I found this in 2 places - there may be more.  Try with the usual survey data.
a) Filter - then Filter from Factor - select all levels doesn't seem to do anything.
b) Filter , Define New filter and choose a factor.  The select all levels again seems to do nothing.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #7538.

@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

File: instat/ucrFactor.vb [hunk 1]
```diff
@@ -746,9 +746,8 @@ Public Class ucrFactor
         For iRowIndex As Integer = 0 To _grdSheet.Rows - 1
             If _grdSheet(iRowIndex, iCheckedColIndex) <> bChecked Then
                 bChangeDetected = True
-            Else
-                _grdSheet(iRowIndex, iCheckedColIndex) = bChecked
             End If
+            _grdSheet(iRowIndex, iCheckedColIndex) = bChecked
```
Comment (lloyddewit) [inline instat/ucrFactor.vb:750]: move to inside `If` block?

**Review by lloyddewit — CHANGES_REQUESTED** [review]

**Review by rdstern — APPROVED** [review]
Good

File: instat/ucrFactor.vb (hunk 1 above)
Comment (Patowhiz) [reply instat/ucrFactor.vb]: Agreed and done!

**Review by lloyddewit — APPROVED** [review]
