### PR TITLE
layer order bug fix and general graphics dialog display fixed

### LINKED ISSUE #4098: Adding layer to boxplot dialog
I added a layer to the boxplot dialog. It also worked except the second layer appeared under the boxplot, which wasn't very useful. I assume this is just an issue with parameter positions. Can this be fixed? And checked on all other graphics dialogs?

### PR DESCRIPTION
**Pull request by dannyparsons**
fixes #4098

### CODE REVIEW

File: instat/dlgScatterPlot.vb [hunk 1]
```diff
@@ -130,7 +130,7 @@ Public Class dlgScatterPlot
 
         clsBaseOperator.SetOperation("+")
         clsBaseOperator.AddParameter("ggplot", clsRFunctionParameter:=clsRggplotFunction, iPosition:=0)
-        clsBaseOperator.AddParameter("scatter", clsRFunctionParameter:=clsRScatterGeomFunction)
+        clsBaseOperator.AddParameter("scatter", clsRFunctionParameter:=clsRScatterGeomFunction, iPosition:=2)
```
Comment (dannyparsons) [inline instat/dlgScatterPlot.vb]: @maxwellfundi here I have added a position for the geom on all graphics dialogs, this was part of what was needed to solve layer order. I think position 2 is sensible for the first geom layer. Let's remember to add a position to every parameter, it's especially important for ggplot.

File: instat/ucrAdditionalLayers.vb [hunk 2]
```diff
@@ -46,6 +48,7 @@ Public Class ucrAdditionalLayers
             strTempGeomName = GetGeomName(clsTempParam)
             If strTempGeomName <> "" Then
                 AddLayers(strTempGeomName, bFromLayerSubDialog:=False)
+                iParameterPosition = Math.Max(iParameterPosition, clsTempParam.Position)
```
Comment (dannyparsons) [inline instat/ucrAdditionalLayers.vb]: @maxwellfundi here I'm calculating the maximum current position of all geoms to ensure that additional geoms always have a larger position. This needed to be different from iLayerIndex because the layer index always starts at 1, whereas the position depends on the positions of the current layers, which are set on the main dialog.

File: instat/dlgScatterPlot.vb (hunk 1 above)
Comment (maxwellfundi) [reply instat/dlgScatterPlot.vb]: Great, thanks.
