### PR TITLE
changes to Climatic summaries dialog

### LINKED ISSUE #5306: Climatic > Prepare > Climatic Summaries
Another bug in this dialogue that may be easy to find.  I describe briefly and then in more detail with an example, if required.

I am using the dialogue with the Dodoma data (filtered to omit year > 2011 to avoid missing values in the rainfall.)  I have earlier used the **Climatic > Prepare > Transform** dialogue, with **multiple spells** on the rainfall and the condition <=0.85 to give dry-spell lengths.

Now I use the Climatic > Prepare > Climatic Summaries dialogue with the third option for the buttons at the top, i.e. Within Year.  I am summarising the spells by doy.  I am using the one summary on the More button, namely Prop > 7.  I find that after choosing the summary I return to the main dialogue.  I click OK, and it gives me the summary also by Year.  When I return to the dialogue it has changed to the second option.  I make it the third and it runs OK.

I think it is the use of the sub-dialogue that may be causing the problem.  The wrong (and then correct) codes are as follows:

 **Wrong code with "year" added.**
day_filter <- instat_calculation$new(type="filter", function_exp="doy_366 >= 1 & doy_366 <= 366", calculated_from=calc_from_convert(x=list(dodoma="doy_366")))
data_book$calculate_summary(columns_to_summarise="spells", data_name="dodoma", **factors=c("year", "doy_366"),** additional_filter=day_filter, prop_value=15, prop_test="'>'", summaries=c("proportion_calc"), silent=TRUE) 

**Correct Code** 
day_filter <- instat_calculation$new(type="filter", function_exp="doy_366 >= 1 & doy_366 <= 366", calculated_from=calc_from_convert(x=list(dodoma="doy_366")))
data_book$calculate_summary(columns_to_summarise="spells", data_name="dodoma", **factors=c("doy_366"),** additional_filter=day_filter, prop_value=15, prop_test="'>'", summaries=c("proportion_calc"), silent=TRUE)

### PR DESCRIPTION
**Pull request by Ivanluv**
fixes #5306 
@africanmathsinitiative/developers  this can be reviewed

### CODE REVIEW

File: instat/dlgClimaticSummary.vb [hunk 1]
```diff
@@ -301,4 +303,11 @@ Public Class dlgClimaticSummary
             ucrInputFilterPreview.SetName(clsFromAndToConditionOperator.ToScript())
         End If
     End Sub
+    Private Sub UpdateRCode()
+        If rdoAnnual.Checked Then
+            clsDefaultFactors.RemoveParameterByName("within_variable")
+        ElseIf rdoWithinYear.Checked Then
+            clsDefaultFactors.RemoveParameterByName("year")
+        End If
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: This looks good but shouldn't it go under the event `ucrPnlAnnualWithin.ControlValueChanged`? I think this should happen then too.

Also, I'm surprised there isn't any adding parameters in here. If I go from Annual to WithinYear and then back to Annual, does the year parameter get added back in?

Comment (Ivanluv) [reply instat/dlgClimaticSummary.vb]: when I put it under `ucrPnlAnnualWithin.ControlValueChanged?` it still gives me the bug.
The parameters year and withhin year are added when setting the Rcode so am just removing the parameters when the respective radio buttons are checked.So the parameters already exist ,thats why am not adding the parameters

**Comment by Ivanluv** [comment]
@maxwellfundi  would you please look at this

File: instat/dlgClimaticSummary.vb [hunk 2]
```diff
@@ -204,11 +204,6 @@ Public Class dlgClimaticSummary
         ucrChkPrintOutput.SetRCode(clsDefaultFunction, bReset)
 
         ucrPnlAnnualWithin.SetRCode(clsDefaultFactors, bReset)
-        ucrReceiverStation.SetRCode(clsDefaultFactors, bReset)
-        ucrReceiverYear.SetRCode(clsDefaultFactors, bReset)
-        ucrReceiverWithinYear.SetRCode(clsDefaultFactors, bReset)
```
Comment (maxwellfundi) [inline instat/dlgClimaticSummary.vb]: Why is this removed @Ivanluv ?

**Comment by shadrackkibet** [comment]
@Ivanluv ?

**Comment by Ivanluv** [comment]
@shadrackkibet  this can be reviewed

**Comment by shadrackkibet** [comment]
Please sort out conflicting files.

**Comment by dannyparsons** [comment]
that should be ok now

**Comment by shadrackkibet** [comment]
great, testing this now.

File: instat/dlgClimaticSummary.vb [hunk 3]
```diff
@@ -337,6 +335,25 @@ Public Class dlgClimaticSummary
...
+            End If
+            If Not clsDefaultFactors.ContainsParameter("year") Then
+                clsDefaultFactors.AddParameter(ucrReceiverYear.GetParameter())
+            End If
+        ElseIf rdoWithinYear.Checked Then
+            If clsDefaultFactors.ContainsParameter("year") Then
+                clsDefaultFactors.RemoveParameterByName("year")
+            End If
+            clsDefaultFactors.AddParameter(ucrReceiverWithinYear.GetParameter())
+
```
Comment (shadrackkibet) [inline instat/dlgClimaticSummary.vb]: End sub missing?

Comment (shadrackkibet) [reply instat/dlgClimaticSummary.vb]: End if?

Comment (shadrackkibet) [reply instat/dlgClimaticSummary.vb]: Make these minor changes so that I can test this.

**Comment by maxwellfundi** [comment]
@Ivanluv  there a very few and little changes needed here. Could you please try make them so that this can be tested.

**Comment by shadrackkibet** [comment]
@dannyparsons this is now working fine. This is ready for you.

File: instat/dlgClimaticSummary.vb [hunk 4]
```diff
@@ -337,6 +335,26 @@ Public Class dlgClimaticSummary
         End If
     End Sub
 
+    Private Sub UpdateRCode()
+        If rdoAnnual.Checked Then
+            If clsDefaultFactors.ContainsParameter("within_variable") Then
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: You don't need to check if the parameter is there, when you run remove line it will do nothing if the parameter is not there.

File: instat/dlgClimaticSummary.vb [hunk 5]
```diff
@@ -337,6 +335,26 @@ Public Class dlgClimaticSummary
...
+                clsDefaultFactors.RemoveParameterByName("within_variable")
+            End If
+            clsDefaultFactors.AddParameter(ucrReceiverYear.GetParameter())
+        ElseIf rdoAnnualWithinYear.Checked Then
+            If Not clsDefaultFactors.ContainsParameter("within_variable") Then
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: You don't need to check if its not there, it doesn't matter if it gets added when its already there. But you should check the the receiver isn't empty before adding.

File: instat/dlgClimaticSummary.vb [hunk 6]
```diff
@@ -337,6 +335,26 @@ Public Class dlgClimaticSummary
...
+                clsDefaultFactors.AddParameter(ucrReceiverWithinYear.GetParameter())
+            End If
+            If Not clsDefaultFactors.ContainsParameter("year") Then
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: Just check receiver is not empty.

File: instat/dlgClimaticSummary.vb [hunk 7]
```diff
@@ -337,6 +335,26 @@ Public Class dlgClimaticSummary
...
+                clsDefaultFactors.AddParameter(ucrReceiverYear.GetParameter())
+            End If
+        ElseIf rdoWithinYear.Checked Then
+            If clsDefaultFactors.ContainsParameter("year") Then
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: No need to check this first.

File: instat/dlgClimaticSummary.vb [hunk 8]
```diff
@@ -337,6 +335,26 @@ Public Class dlgClimaticSummary
...
+                clsDefaultFactors.RemoveParameterByName("year")
+            End If
+            clsDefaultFactors.AddParameter(ucrReceiverWithinYear.GetParameter())
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: Check that the receiver is not empty before adding.

File: instat/dlgClimaticSummary.vb [hunk 9]
```diff
@@ -311,6 +308,7 @@ Public Class dlgClimaticSummary
 
     Private Sub ucrPnlAnnualWithin_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrPnlAnnualWithin.ControlValueChanged
         WithinYearLabelReceiverLocation()
+        UpdateRCode()
```
Comment (dannyparsons) [inline instat/dlgClimaticSummary.vb]: You'll need to run this when any of the receivers change as well once the checks for empty are added.

**Comment by shadrackkibet** [comment]
There is an issue with this dialog when using the last option (Within Year) and then click ok.  When the dialog is reopened it returns back to the middle option(Annual+within year). I thought this was reported somewhere and fixed! I couldn't trace it. This is all about setting conditions properly for the top panel. Could you please have a look at it?

**Comment by Ivanluv** [comment]
> There is an issue with this dialog when using the last option (Within Year) and then click ok. When the dialog is reopened it returns back to the middle option(Annual+within). I thought this was reported somewhere and fixed! I couldn't trace it. This is all about setting conditions properly for the top panel. Could you please have a look at it?

Am not getting this error from my end

**Comment by shadrackkibet** [comment]
Try checking one of the options under missing value options tab first, click ok and then reopen you should be able to notice that the dilaog resets to the middle option.

**Comment by maxwellfundi** [comment]
@shadrackkibet  could you update your branch, it appears that  the last bug you reported was fixed by @Ivanluv in another PR.

**Comment by shadrackkibet** [comment]
The bug is there. I will discuss with @Ivanluv on skype

**Comment by maxwellfundi** [comment]
great thank you

**Comment by Ivanluv** [comment]
@shadrackkibet  I've made a temporary fix to the Panel
