### PR TITLE
Partially Fixes issue #6903 ( Prepare>Data Reshape>Random Subset )

### LINKED ISSUE #6903: Change "Random Subset" to be consistent with Tidyverse
I have been looking at the dialogs in the "Data Reshape" sub-menu to check for consistencies with Tidyverse.

Under `Prepare > Data Reshape > Random Subset` the dialog currently uses the functions `data.frame`, `replicate`, and `sample` to randomly sample n rows from a column in the data frame. 
`replicate` and `sample` can be updated to use functions from the `Tidyverse` set of packages.

### **`replicate`**
`replicate` is a function from the base package. Instead, `rerun` in the `purrr` package can be used.

`replicate(n = ..., expr = ...)`

can just change to

`purrr::rerun(.n = ..., expr = ...)`

Changes made:
* the function `replicate` changes to `rerun` in the `purrr` package.
* the parameter `n` changes to `.n`

### **`sample`**
`sample` is a function from the base package. Instead, `sample_n` in the `dplyr` package can be used.
The parameters remain similar between the two options.

```
sample(x = <variable>, 
       size = <value>,
       replace = <logical>)
```

can just change to

```
dplyr::sample_n(tbl = data.frame(<variable>),
                size = <value>,
                replace = <logical>)
```

* the function `sample` changes to `sample_n` in the `dplyr` package.
* the parameter `x` changes to `tbl`
* `tbl` now equals a `data.frame` function with the variable as a parameter in the data.frame function
* `replace = FALSE` remains the default.

The `sample_frac` option could potentially be added.
This function takes the sample parameters as `sample_n`, but the `size` parameter can only take values between 0 and 1 inclusive. This is because the `size` option is now the fraction of rows to use.

@rdstern what do you think of these suggestions?

### PR DESCRIPTION
**Pull request by EstherNjeriLiberatta**
Fixes #6903 In this PR I have made the requested changes as suggested by @lilyclements .

@rdstern @lilyclements Kindly review.
@africanmathsinitiative/developers This is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv Please could you review? thanks

**Review by Ivanluv — DISMISSED** [review]

File: instat/dlgRandomSubsets.vb [hunk 1]
```diff
@@ -18,7 +18,7 @@ Imports instat.Translations
 Public Class dlgRandomSubsets
     Public bFirstLoad As Boolean = True
     Private bReset As Boolean = True
-    Private clsDataFrame, clsSetSeed, clsSample, clsReplicate As New RFunction
+    Private clsDataFrameFunction, clsSampleNFunctionDataframeFunction, clsSetSeed, clsSampleFunction, clsRerunFunction As New RFunction
```
Comment (lloyddewit) [inline instat/dlgRandomSubsets.vb:21]: Thanks for naming these `...Function`, this helps readability. 
Should we also rename `clsSetSeed` to `clsSetSeedFunction` for consistency?

**Review by lloyddewit — CHANGES_REQUESTED** [review]
@EstherNjeriLiberatta Looks good, just one small comment

**Comment by EstherNjeriLiberatta** [comment]
@lloyddewit I have made the requested changes. Thanks

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Comment by rdstern** [comment]
image

a) Please check the code.  You can see I don't get 10 columns here, just 2.  Ask @HawardKetoyoMsatsi or others if you need help.
b) I used the checkbox to set the seed.  When I return to the dialogue, it is unchecked.  It should remember it was checked before.  The other controls do all seem to remember.

**Review by rdstern — CHANGES_REQUESTED** [review]
Comments given for changes needed

**Comment by EstherNjeriLiberatta** [comment]
@rdstern I have fixed the changes you requested. Kindly review.

@africanmathsinitiative/developers This is ready for review.

**Review by rdstern — DISMISSED** [review]
@EstherNjeriLiberatta great.  This now seems to work fine.

File: instat/dlgRandomSubsets.vb [hunk 2]
```diff
@@ -130,7 +142,7 @@ Public Class dlgRandomSubsets
 
     Private Sub ucrBase_BeforeClickOk(sender As Object, e As EventArgs) Handles ucrBase.BeforeClickOk
         If ucrChkSetSeed.Checked Then
-            frmMain.clsRLink.RunScript(clsSetSeed.ToScript(), strComment:="dlgRandomSubset: Setting the seed for random number generator")
+            frmMain.clsRLink.RunScript(clsSetSeedFunction.ToScript(), strComment:="dlgRandomSubset: Setting the seed for random number generator")
         End If
     End Sub
```
Comment (shadrackkibet) [inline instat/dlgRandomSubsets.vb:147]: This should change. We should run this when set seed checkbox state changes i.e ....controlValue changed event. Then we should do this as before codes. So something like this.
```
    Private Sub ucrChkSetSeed_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrChkSetSeed.ControlValueChanged
        If ucrChkSetSeed.Checked Then
            ucrBase.clsRsyntax.AddToBeforeCodes()
        Else
            ucrBase.clsRsyntax.RemoveFromBeforeCodes()
        End If
    End Sub
```

Remember to clear codes in setdefault.

File: instat/dlgRandomSubsets.vb [hunk 3]
```diff
@@ -70,46 +71,57 @@ Public Class dlgRandomSubsets
...
+        clsRerunFunction.SetRCommand("rerun")
+        clsRerunFunction.AddParameter(".n", 1)
+        clsRerunFunction.AddParameter("expr", clsRFunctionParameter:=clsSampleFunction)
 
-        'replicate func setting
-        clsReplicate.SetRCommand("replicate")
-        clsReplicate.AddParameter("n", 1)
-        clsReplicate.AddParameter("expr", clsRFunctionParameter:=clsSample)
+        'sample_n dataframe func setting
+        clsSampleNFunctionDataframeFunction.SetRCommand("data.frame")
```
Comment (shadrackkibet) [inline instat/dlgRandomSubsets.vb:107]: Remove this function because we can force `get_columns_from_data()` to extract a single column as a dataframe by doing
`ucrReceiverSubsets.bForceAsDataFrame = True` on initialise.

**Review by shadrackkibet — CHANGES_REQUESTED** [review]
@EstherNjeriLiberatta well done. This is good progress.

I have reviewed your PR by adding in comments and suggestions where possible. I hope these comments are useful to improve the code. Let me know if something isn't clear enough. I am happy to write more here to explain if you feel something isn't clear or even follow up elsewhere.

**Comment by EstherNjeriLiberatta** [comment]
@africanmathsinitiative/developers This is ready for review.

File: instat/dlgRandomSubsets.vb [hunk 4]
```diff
@@ -184,9 +177,15 @@ Public Class dlgRandomSubsets
...
+            ucrBase.clsRsyntax.AddToBeforeCodes(clsSetSeedFunction)
         Else
-            clsDummyFunction.AddParameter("checked", "false", iPosition:=0)
+            ucrBase.clsRsyntax.RemoveFromBeforeCodes(clsSetSeedFunction)
+        End If
+    End Sub
+
+    Private Sub ucrBase_BeforeClickOk(sender As Object, e As EventArgs) Handles ucrBase.BeforeClickOk
+        If ucrChkSetSeed.Checked Then
+            frmMain.clsRLink.RunScript(clsSetSeedFunction.ToScript(), strComment:="dlgRandomSubset: Setting the seed for random number generator")
```
Comment (shadrackkibet) [inline instat/dlgRandomSubsets.vb:188]: Do you still need this? I see it already in line 180.

**Review by shadrackkibet — CHANGES_REQUESTED** [review]

**Comment by EstherNjeriLiberatta** [comment]
@shadrackkibet Thank you for the corrections. 
@africanmathsinitiative/developers This is ready for review.

**Review by rdstern — DISMISSED** [review]
Still works ok for me

File: instat/dlgRandomSubsets.vb [hunk 5]
```diff
@@ -70,46 +72,54 @@ Public Class dlgRandomSubsets
...
 
-        'replicate func setting
-        clsReplicate.SetRCommand("replicate")
-        clsReplicate.AddParameter("n", 1)
-        clsReplicate.AddParameter("expr", clsRFunctionParameter:=clsSample)
+        'rerun func setting
+        clsRerunFunction.SetPackageName("purrr")
+        clsRerunFunction.SetRCommand("rerun")
+        clsRerunFunction.AddParameter(".n", 1)
+        clsRerunFunction.AddParameter("expr", clsRFunctionParameter:=clsSampleFunction)
```
Comment (shadrackkibet) [inline instat/dlgRandomSubsets.vb:102]: With parameter names, the position doesn't matter. For consistency, always add parameter positions. Check other places as well.

File: instat/dlgRandomSubsets.vb [hunk 6]
```diff
@@ -169,4 +174,12 @@ Public Class dlgRandomSubsets
     Private Sub CoreControls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrNudNumberOfColumns.ControlContentsChanged, ucrNudSampleSize.ControlContentsChanged, ucrNudSetSeed.ControlContentsChanged, ucrNewDataFrame.ControlContentsChanged, ucrChkSetSeed.ControlContentsChanged, ucrReceiverSubsets.ControlContentsChanged
         TestOKEnabled()
     End Sub
```
Comment (shadrackkibet) [inline instat/dlgRandomSubsets.vb:176]: I like to make this the last `sub`

File: instat/dlgRandomSubsets.vb [hunk 7]
```diff
@@ -37,7 +37,8 @@ Public Class dlgRandomSubsets
         ucrBase.iHelpTopicID = 65
 
         'ucrReceiver
-        ucrReceiverSubsets.SetParameter(New RParameter("x", 2))
+        ucrReceiverSubsets.bForceAsDataFrame = True
```
Comment (shadrackkibet) [inline instat/dlgRandomSubsets.vb:40]: Since you now have this. Should just remove `clsSampleNFunctionDataframeFunction`

**Review by shadrackkibet — CHANGES_REQUESTED** [review]

File: instat/dlgRandomSubsets.vb (hunk 5 above)
Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:102]: Alright, thanks.

File: instat/dlgRandomSubsets.vb (hunk 6 above)
Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:176]: Okay

File: instat/dlgRandomSubsets.vb (hunk 7 above)
Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:40]: I need that function to convert the variable in the sample_n function into a data frame that is;
`sample_n (data.frame(<variable>), size=...)`. It didn't work when I removed it.

I also decided to keep `bIncludeArgumentName:= False` in line 40 as it is because I did not want `x`  to appear within the function e.g. `sample_n (data.frame(x=field), size=...)`. I would like the R code to look simple. Thanks.

Comment (shadrackkibet) [reply instat/dlgRandomSubsets.vb:40]: You mention that " It didn't work when I removed it". What exactly do you mean? Did it give an error? If yes which error message? Did you get an exception etc... 

Just saying that things didn't work doesn't help me to help you.

Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:40]: Okay, sorry. I guess I can show you what the R code looks like. I didn't know how best to explain it.
The function is on the second highlight. Thanks for helping.

image

Comment (shadrackkibet) [reply instat/dlgRandomSubsets.vb:40]: Does this work for you?
```

# Code generated by the dialog, Random Subsets

field <- data_book$get_columns_from_data(data_name="survey", col_names="field", force_as_data_frame=TRUE)
survey_random <- data.frame(X=purrr::rerun(.n=1, expr=dplyr::sample_n(tbl=field, size=36)))
data_book$import_data(data_tables=list(survey_random=survey_random))

rm(list=c("survey_random", "field"))
```

Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:40]: No, the field variable has to be converted into a data frame in the function `sample_n()`

Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:40]: It should be `sample_n(tbl=data.frame(<variable>),...`

Comment (shadrackkibet) [reply instat/dlgRandomSubsets.vb:40]: Isn't it already a data frame when you do this? `field <- data_book$get_columns_from_data(data_name="survey", col_names="field", force_as_data_frame=TRUE)`

Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:40]: I get this error when I try that. 
```
field <- data_book$get_columns_from_data(data_name="survey", col_names="field", col_names="field", force_as_data_frame=TRUE)
survey_random2 <-data.frame(X=purrr::rerun(.n=4, expr=dplyr::sample_n(tbl=field, size=36)))
data_book$import_data(data_tables=list(survey_random2=survey_random2))
```

image

Comment (shadrackkibet) [reply instat/dlgRandomSubsets.vb:40]: That is because you have `col_names` twice in this line; 

`data_book$get_columns_from_data(data_name="survey", col_names="field", col_names="field", force_as_data_frame=TRUE)`

Comment (EstherNjeriLiberatta) [reply instat/dlgRandomSubsets.vb:40]: May I contact you on skype, if you don't mind

Comment (shadrackkibet) [reply instat/dlgRandomSubsets.vb:40]: Sure

Comment (shadrackkibet) [reply instat/dlgRandomSubsets.vb:40]: Resolved over skype.

**Comment by EstherNjeriLiberatta** [comment]
I made corrections to the code:
i. Removed `clsSampleNDataFrameFunction` as it was repeating what `ucrReceiverSubsets.bForceAsDataFrame = True` was doing i.e. converting the varibles into a data frame.
ii. Added parameter positions to all parameters for consistency.

@shadrackkibet Thank you.
@africanmathsinitiative/developers This is ready for review.

**Comment by shadrackkibet** [comment]
@rdstern could you test and re-approve? In theory, there shouldn't be any functionality change since your last approval.

@EstherNjeriLiberatta just to let you know that I made a small edit in the `clsRSyntax.vb` file.

image

**Review by rdstern — APPROVED** [review]
Well done.  Seems fine to me

**Review by shadrackkibet — APPROVED** [review]
