### PR TITLE
Export open refine

### LINKED ISSUE #4956: Prepare > Check Data > Export to Open Refine
**Describe the bug**
Going into this dialogue gives the error message:

**instat
This name cannot start with _
OK**   

It happens consistently.  It then goes into the dialogue.

### PR DESCRIPTION
**Pull request by Muthenya**
Fixes #4956 
@maxwellfundi please have a look at this.

### CODE REVIEW

File: instat/dlgExportToOpenRefine.vb [hunk 1]
```diff
@@ -69,7 +69,7 @@ Public Class dlgExportToOpenRefine
 
         clsDefaultRefine.SetPackageName("rrefine")
         clsDefaultRefine.SetRCommand("refine_upload")
-        clsDefaultRefine.AddParameter("project.name", ucrDataFrameOpenRefine.cboAvailableDataFrames.SelectedItem & "_clean_up")
+        clsDefaultRefine.AddParameter("project.name", Chr(34) & ucrInputDatasetName.GetText() & Chr(34))
```
Comment (dannyparsons) [inline instat/dlgExportToOpenRefine.vb]: why remove `"_clean_up"`?

Comment (Muthenya) [reply instat/dlgExportToOpenRefine.vb]: It is not really required here, since the text from the text box already has it. Adding it results in it being added to the name each time reset is clicked.
