### PR TITLE
Fixed bug on Climatic > Inventory Plot dialog

### LINKED ISSUE #7015: Problem with the Output Window when trying the Climatic > Check data > Inventory Plot
I have tried to plot the inventory of the `Dodoma ` data using the `Inventory Plot` but I'm getting the following error in the screenshot below.
image

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7015 
@dannyparsons @ChrisMarsh82  I have tried to fix the bug on the InventoryPlot, please take a look.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@N-thony that's a releif - it seems to work again!

File: instat/Model/Output/clsOutputElement.vb [hunk 1]
```diff
@@ -109,6 +109,10 @@ Public Class clsOutputElement
     ''' <param name="strScript"></param>
     Public Sub AddScript(strScript As String)
         Dim rScript As New clsRScript(strScript)
+        If rScript.GetLstTokens(rScript.GetLstLexemes(strScript)) Is Nothing Then
```
[the remark this answers is not in the document]
Comment (N-thony) [reply instat/Model/Output/clsOutputElement.vb]: @dannyparsons I resolved this. Please take a look. Thanks.

File: instat/UserControl/ucrOutputPage.vb [hunk 2]
```diff
@@ -159,6 +159,10 @@ Public Class ucrOutputPage
     End Sub
 
     Private Function AddElementPanel(outputElement As clsOutputElement) As Panel
+        If outputElement.FormatedRScript Is Nothing Then
+            Exit Function
```
Comment (lloyddewit) [inline instat/UserControl/ucrOutputPage.vb:163]: 'Exit Function' is normally used to return a value that was set earlier, e.g.:
``` 
'Returns "Hello"
Private Function Example2() As String
  Example2 = "Hello"
  Exit Function
End Function
```
On line 163, it will return `Nothing`. This is correct but it is clearer to write `Return Nothing`.

File: instat/UserControl/ucrOutputPage.vb [hunk 3]
```diff
@@ -159,6 +159,10 @@ Public Class ucrOutputPage
     End Sub
 
     Private Function AddElementPanel(outputElement As clsOutputElement) As Panel
+        If outputElement.FormatedRScript Is Nothing Then
```
Comment (lloyddewit) [inline instat/UserControl/ucrOutputPage.vb:162]: If `outputElement` is `Nothing`, then this line triggers an exception. Would it be safer to write:
```suggestion
        If outputElement Is Nothing OrElse outputElement.FormatedRScript Is Nothing Then
```

**Review by lloyddewit — CHANGES_REQUESTED** [review]

File: instat/UserControl/ucrOutputPage.vb (hunk 2 above)
Comment (N-thony) [reply instat/UserControl/ucrOutputPage.vb]: @lloyddewit many thanks for this. You are right.

Comment (N-thony) [reply instat/UserControl/ucrOutputPage.vb]: @lloyddewit I have resolved your comment. Please take a look. Thanks.

**Review by dannyparsons — APPROVED** [review]
Tested and this works well.

**Comment by N-thony** [comment]
@rdstern could you test/approve? Thanks.

**Review by rdstern — APPROVED** [review]

**Review by lloyddewit — APPROVED** [review]
