### PR TITLE
dlgSPI/SPEI updated to allow multiple stations and bug fixes

### LINKED ISSUE #6117: Improve design of SPI/SPEI dialog
Once the SPI/SPEI dialog updates are merged here #6116 the dialog design could be improved. I suggest:

- The SPI/SPEI option becomes button type radio buttons at the top of the dialog
- Kernel Type becomes a combo box
- Time Scale should include "Month" in some ways as it's a number of months. Possibly "Time Scale (Months)"

It would be good to consider the general positioning of the options on the dialog to see if there's a nicer way to organise them.

@lilyclements are you able to take this task?

### PR DESCRIPTION
**Pull request by lilyclements**
Replaces #6116 

Fixes #6117 

@africanmathsinitiative/developers this is ready for review.

This PR fixes a few bugs and has some design alterations. Additionally, changes from #6116 :

> * dialog now allows multiple stations
> * wrapper R functions added to organise input and output data
> 
> **To test**
> 
> * Dialog is for monthly data only
> * Data must be in date order (within stations)
> * Data can't have any gaps i.e. missing months
> The dialog should get sensible errors if any of these are not met.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet Please could you review? thanks
Sorry that I'm currently asking you to do most of the reviews. Your review observations increase the code quality. and you are the best qualified developer to do the reviews at the moment. The number of reviews needed may decrease in the next weeks but if the review requests get too much then let me know.

File: instat/dlgSPI.vb [hunk 1]
```diff
@@ -35,35 +39,37 @@ Public Class dlgSPI
     End Sub
 
     Private Sub InitialiseDialog()
+        Dim dctType As New Dictionary(Of String, String)
         ucrBase.clsRsyntax.iCallType = 2
```
Comment (shadrackkibet) [inline instat/dlgSPI.vb:43]: Nothing is printed in the output window. Remove?

File: instat/static/InstatObject/R/stand_alone_functions.R [hunk 2]
```diff
@@ -1565,3 +1565,78 @@ make_factor <- function(x, ordered = is.ordered(x)) {
...
+  cols <- c(id_cols, element)
+  start <- c(data[[year]][1], data[[month]][1])
+  # If multiple stations, needs to be in "wide" format for SPEI
+  if (!missing(station)) {
+    ts_data <- tidyr::pivot_wider(data, id_cols = tidyselect::all_of(c(year, month)), 
+                                  names_from = tidyselect::all_of(station), values_from = tidyselect::all_of(element),
+                                  values_fill = NA)
+    ts_data <- ts_data %>% dplyr::arrange(!!! rlang::syms(c(year, month)))
+    # Not sure how to do this using dplyr::select
+    ts_data[id_cols] <- NULL
```
Comment (shadrackkibet) [inline instat/static/InstatObject/R/stand_alone_functions.R:1601]:
```suggestion
  ts_data <- tidyr::pivot_wider(data,
  id_cols = tidyselect::all_of(c(year, month)),
  names_from = tidyselect::all_of(station), values_from = tidyselect::all_of(element),
  values_fill = NA) %>%
  dplyr::arrange(!!!rlang::syms(c(year, month))) %>%
  dplyr::select(!c(year, month))
```

**Review by shadrackkibet — CHANGES_REQUESTED** [review]

**Comment by shadrackkibet** [comment]
> @shadrackkibet Please could you review? thanks
> Sorry that I'm currently asking you to do most of the reviews. Your review observations increase the code quality. and you are the best qualified developer to do the reviews at the moment. The number of reviews needed may decrease in the next weeks but if the review requests get too much then let me know.

@lloyddewit I am happy to review. No worries!

**Comment by dannyparsons** [comment]
Thanks @shadrackkibet I've addressed these comments here https://github.com/africanmathsinitiative/R-Instat/pull/6123

File: instat/static/InstatObject/R/stand_alone_functions.R (hunk 2 above)
Comment (lloyddewit) [reply instat/static/InstatObject/R/stand_alone_functions.R:1601]: @dannyparsons You implemented @shadrackkibet 's comment above with the exception of the `%>% dplyr::select(!c(year, month))` part.
I was expecting to see a line similar to:
```
ts_data <- ts_data %>% dplyr::select(!c(year, month))
```
Was this omitted deliberately?

Comment (dannyparsons) [reply instat/static/InstatObject/R/stand_alone_functions.R:1601]: Yes, that didn't quite work because the column names are string variables, which needs a different syntax in `dplyr` but I couldn't quite figure out how to do this. In any case, it gives the same functionality.
