### PR TITLE
Small design fixes in Enter dialog

### LINKED ISSUE #6454: Problems with the French translation version
This is partly just for information for @lloyddewit and partly for @N-thony because he will be interested in improving the French version.
It is largely occasions where the labels are too long in French.  But there are some other issues too - as we expected.

It is not yet in order, but just as I use the dialogues:
a) Prepare > Data: Calculations  > Enter
image

- [x] Why is the header (ENTREE) in capitals?  It is in lower case in English. (moved this part of the issue to issue #6464)
- [x]  The 2 controls in the data line are too long.  The first also is important to fix soon, because the first numbers typed are hidden.  
- [ ] The keys are translated.  Is this correct?
- [x] Not visible here, but if you press Lan to go into English, then the label (Entrer les resultats dans) stays in French.  (Fixed in PR #6469)

### PR DESCRIPTION
**Pull request by N-thony**
@rdstern @lloyddewit this partially fixes #6454.

### CODE REVIEW

File: instat/dlgClimaticDataEntry.vb [hunk 1]
```diff
@@ -32,6 +32,7 @@ Public Class dlgClimaticDataEntry
     Private ReadOnly strRange As String = "Range"
     Private bChange As Boolean = False
     Private bSubdialogFirstLoad As Boolean = True
+    Private bRemoveValueChanged As Boolean = True
```
Comment (lloyddewit) [inline instat/dlgClimaticDataEntry.vb:35]: Delete? (see comment below)

File: instat/dlgClimaticDataEntry.vb [hunk 2]
```diff
@@ -43,6 +44,10 @@ Public Class dlgClimaticDataEntry
         If bReset Then
             SetDefaults()
         End If
+        If bRemoveValueChanged Then
+            AddHandler ucrReceiverStation.ControlValueChanged, AddressOf StationControls_ControlValueChanged
+            bRemoveValueChanged = False
+        End If
```
Comment (lloyddewit) [inline instat/dlgClimaticDataEntry.vb:50]: Move the `AddHandler` command could to `InitialiseDialog()` and delete this `If` block?
Is the `AddHandler` even needed? Doesn't the `Handles` on line 307 achieve the same thing?

**Review by lloyddewit — CHANGES_REQUESTED** [review]

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern Please could you test? thanks

**Review by rdstern — APPROVED** [review]
