### PR TITLE
Fixing the Developer error when adding geom_abline layer

### LINKED ISSUE #6211: Developer error when adding geom_abline layer
Adding `geom_abline` layer under Plot Options>Layers prompts you with a developer error. This is confusing to users, it is only meant for developers.
image

### PR DESCRIPTION
**Pull request by Ivanluv**
fixes #6211
@africanmathsinitiative/developers this is ready for review

### CODE REVIEW

File: instat/ucrGeom.vb [hunk 1]
```diff
@@ -1403,7 +1403,7 @@ Public Class ucrGeom
         clsgeom_mosaic.AddLayerParameter("stat", "editablelist", Chr(34) & "mosaic" & Chr(34), lstParameterStrings:={Chr(34) & "mosaic" & Chr(34)}) ' Made this editable because am not sure what other stats go here
         clsgeom_mosaic.AddLayerParameter("position", "editablelist", Chr(34) & "identity" & Chr(34), lstParameterStrings:={Chr(34) & "identity" & Chr(34)}) ' Made this editable because am not sure what other positions go here
         clsgeom_mosaic.AddLayerParameter("colour", "colour", Chr(34) & "black" & Chr(34))
-        clsgeom_abline.AddLayerParameter("size", "numeric", "1", lstParameterStrings:={1, 10}) 'not certain if the size goues up to this much
+        clsgeom_mosaic.AddLayerParameter("size", "numeric", "1", lstParameterStrings:={1, 1}) 'not certain if the size goues up to this much
```
Comment (shadrackkibet) [inline instat/ucrGeom.vb:1406]: Remove the comment now. Since it doesn't make sense again?

**Review by shadrackkibet — CHANGES_REQUESTED** [review]

File: instat/ucrGeom.vb (hunk 1 above)
Comment (Ivanluv) [reply instat/ucrGeom.vb]: I have removed it

**Review by shadrackkibet — APPROVED** [review]
@rdstern please test.

**Review by rdstern — APPROVED** [review]
